### ISSUE TITLE
Compléments au format csv

### ISSUE THREAD

**Issue by PhML** [ToulouseDataViz/Hackaviz2020#3]
Bonjour,

serait-il possible d’avoir les complément au format CSV en pas uniquement en xlsx ?

Merci

**Comment by ToulouseDataViz** [comment]
Le fichier est constitué de 3 onglets ! Au cas ou vous n'arriviez pas à lire ce fichier, nous l'avons placé sur google drive  :  https://drive.google.com/file/d/14ntwSruYk0B4SN5vydbC_v1WCOvWPbKA/view?usp=sharing

**Comment by ToulouseDataViz** [comment]
Le fichier zipfiles/complements.zip contient désormais le fichier xlsx + les trois onglets au format csv (;)
